### PR TITLE
Simplified tool

### PR DESCRIPTION
**Pull request by sklencar**
The tool completely moved to processing toolbox - deleted toolbar buttons, precision spinbox moved to toolbox widget.

### CODE REVIEW

**Comment by saberraz** [comment]
@sklencar any reason it is limited to 4, 6 and 8 digits precision? Could you add, 0 (just letters), 2 and 10 digits too?

**Comment by sklencar** [comment]
@saberraz The precision was limited to 4-8 digits in the previous version, so it was kept as it was. The reason of that limit could be possible related to zoom level since precision was determined by that. However, now its defined by the precision field and can be extended for the next release.

**Comment by tomchadwin** [comment]
@mtravis If you rerun the tests from https://travis-ci.org/mtravis/gridref-qgis/pull_requests, they should pass, I guess (as we're not really testing much yet).

**Comment by mtravis** [comment]
They don't work but we have already merged these then @tomchadwin ran the
test - which passed.

I guess we can ignore these?

**Pull request merged**
