### PR TITLE
Added precision option

### PR DESCRIPTION
**Pull request by sklencar**
Added a spinbox for defining coordinates precision. Number equals to number of digits in coordinate shown in box and processing toolbox panel.

### CODE REVIEW

**Comment by mtravis** [comment]
Does it matter that the Travis build didn't work?

**Comment by sklencar** [comment]
I have pushed new changes and sent new pull request. However, the build is still broken. Log: [https://travis-ci.org/mtravis/gridref-qgis/builds/328974624?utm_source=github_status&utm_medium=notification](url)

Seems like problem with rake on the server, doesnt it? Can you please help me sort it out?

**Comment by mtravis** [comment]
Hi Victor

I've just downloaded your version of the plugin and had a look. I'm struggling to figure out how you change the precision?

I've no idea why those build errors are coming up or how to fix them. I don't have a lot of spare time at the moment but happy to follow instructions.

**Comment by mtravis** [comment]
I've noticed the precision dial now. There's no way for the user to see what the precision is set at though?

**Comment by mtravis** [comment]
I'm currently looking into this with @tomchadwin

**Comment by sklencar** [comment]
Currently, the value of precision is "hidden", but you can see it directly on coordinates. Their format (precision) suppose to change every time on spinbox value is changed.  I have omitted that field to simplify the tool. 

However, do you suggest to bring it back with visible value for precision?

Thanks a lot for helping!

**Comment by mtravis** [comment]
No worries.

Yes I think we should definitely have a visible value for the user.

**Pull request merged**
